<<<<<<< HEAD
# Generated by Django 4.2.20 on 2025-03-18 15:28
=======
# Generated by Django 4.2.20 on 2025-03-18 15:22
>>>>>>> 8bcd846f35c665c570468f44482c22474452ae3e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
